// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/ingestor/v1/ingestor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_proto_ingestor_v1_ingestor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingestor_v1_ingestor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_proto_ingestor_v1_ingestor_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IngestRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *IngestRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_proto_ingestor_v1_ingestor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingestor_v1_ingestor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_ingestor_v1_ingestor_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_ingestor_v1_ingestor_proto protoreflect.FileDescriptor

const file_proto_ingestor_v1_ingestor_proto_rawDesc = "" +
	"\n" +
	" proto/ingestor/v1/ingestor.proto\x12\vingestor.v1\"z\n" +
	"\rIngestRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\">\n" +
	"\x0eIngestResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2T\n" +
	"\x0fIngestorService\x12A\n" +
	"\x06Ingest\x12\x1a.ingestor.v1.IngestRequest\x1a\x1b.ingestor.v1.IngestResponseB>Z<github.com/mohammad-farrokhnia/go-ingestor/proto/ingestor/v1b\x06proto3"

var (
	file_proto_ingestor_v1_ingestor_proto_rawDescOnce sync.Once
	file_proto_ingestor_v1_ingestor_proto_rawDescData []byte
)

func file_proto_ingestor_v1_ingestor_proto_rawDescGZIP() []byte {
	file_proto_ingestor_v1_ingestor_proto_rawDescOnce.Do(func() {
		file_proto_ingestor_v1_ingestor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ingestor_v1_ingestor_proto_rawDesc), len(file_proto_ingestor_v1_ingestor_proto_rawDesc)))
	})
	return file_proto_ingestor_v1_ingestor_proto_rawDescData
}

var file_proto_ingestor_v1_ingestor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ingestor_v1_ingestor_proto_goTypes = []any{
	(*IngestRequest)(nil),  // 0: ingestor.v1.IngestRequest
	(*IngestResponse)(nil), // 1: ingestor.v1.IngestResponse
}
var file_proto_ingestor_v1_ingestor_proto_depIdxs = []int32{
	0, // 0: ingestor.v1.IngestorService.Ingest:input_type -> ingestor.v1.IngestRequest
	1, // 1: ingestor.v1.IngestorService.Ingest:output_type -> ingestor.v1.IngestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ingestor_v1_ingestor_proto_init() }
func file_proto_ingestor_v1_ingestor_proto_init() {
	if File_proto_ingestor_v1_ingestor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ingestor_v1_ingestor_proto_rawDesc), len(file_proto_ingestor_v1_ingestor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ingestor_v1_ingestor_proto_goTypes,
		DependencyIndexes: file_proto_ingestor_v1_ingestor_proto_depIdxs,
		MessageInfos:      file_proto_ingestor_v1_ingestor_proto_msgTypes,
	}.Build()
	File_proto_ingestor_v1_ingestor_proto = out.File
	file_proto_ingestor_v1_ingestor_proto_goTypes = nil
	file_proto_ingestor_v1_ingestor_proto_depIdxs = nil
}
