// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: ingestor/v1/ingestor.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	IngestorService_Ingest_FullMethodName = "/ingestor.v1.IngestorService/Ingest"
)

// IngestorServiceClient is the client API for IngestorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestorServiceClient interface {
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
}

type ingestorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestorServiceClient(cc grpc.ClientConnInterface) IngestorServiceClient {
	return &ingestorServiceClient{cc}
}

func (c *ingestorServiceClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, IngestorService_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngestorServiceServer is the server API for IngestorService service.
// All implementations must embed UnimplementedIngestorServiceServer
// for forward compatibility
type IngestorServiceServer interface {
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	mustEmbedUnimplementedIngestorServiceServer()
}

// UnimplementedIngestorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIngestorServiceServer struct {
}

func (UnimplementedIngestorServiceServer) Ingest(context.Context, *IngestRequest) (*IngestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedIngestorServiceServer) mustEmbedUnimplementedIngestorServiceServer() {}

// UnsafeIngestorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestorServiceServer will
// result in compilation errors.
type UnsafeIngestorServiceServer interface {
	mustEmbedUnimplementedIngestorServiceServer()
}

func RegisterIngestorServiceServer(s grpc.ServiceRegistrar, srv IngestorServiceServer) {
	s.RegisterService(&IngestorService_ServiceDesc, srv)
}

func _IngestorService_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestorServiceServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestorService_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestorServiceServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IngestorService_ServiceDesc is the grpc.ServiceDesc for IngestorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingestor.v1.IngestorService",
	HandlerType: (*IngestorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _IngestorService_Ingest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingestor/v1/ingestor.proto",
}
